### ISSUE TITLE
AttributeError: 'State' object has no attribute 'stopping_generation'

### ISSUE THREAD

**Issue by TenaciousDean** [Index154/Random-ControlNet-Input#2]
---

<Random ControlNet Input> - Weight pools:
   converted.png: Weight = 1 & image count = 1
    1: Weight = 1 & image count = 32

Will process 1 images, creating 1 new images for each.
*** Error completing request
*** Arguments: ('task(j9mn8myg9gq31fx)', 'A photo of BellaM,  <lora:Emily_epoch_10:0.5>, tactically covered, (((feminine pose))), (((covered nipples)))', '', [], 14, 'Restart', 1, 1, 7, 512, 512, True, 0.51, 2, '4xUltrasharp_4xUltrasharpV10', 15, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x0000017F90123DC0>, 4, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': 'A photo of BellaM, red lipstick, tanned skin', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.52, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <scripts.animatediff_ui.AnimateDiffProcess object at 0x0000017F90806F80>, ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=True, module='openpose_full', model='control_v11p_sd15_openpose [cab727d4]', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode=<ControlMode.CONTROL: 'ControlNet is more important'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.OPENPOSE: 'OpenPose'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='lineart_realistic', model='control_v11p_sd15_lineart [43d4be0d]', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=512, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode=<ControlMode.CONTROL: 'ControlNet is more important'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='lineart_realistic', model='control_v11p_sd15_lineart [43d4be0d]', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=512, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode=<ControlMode.CONTROL: 'ControlNet is more important'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), False, 'Load Only', None, '', 'Send to txt2img', 'Send to img2img', 'Run', None, [], None, None, False, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CUDA', False, 0, 'None', '', None, False, False, 0.5, 0, 'tab_single', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, True, True, 'A:\\AI\\stable-diffusion-webui\\models\\openpose', False, False, True, True, False, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "A:\AI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "A:\AI\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "A:\AI\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "A:\AI\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "A:\AI\stable-diffusion-webui\extensions\Random-ControlNet-Input\scripts\random_controlnet_input.py", line 222, in run
        if state.interrupted or state.stopping_generation:
    AttributeError: 'State' object has no attribute 'stopping_generation'

---

**Comment by Index154** [comment]
That's strange. I can't seem to reproduce the issue. Does this happen on every image you try to generate? Are you doing anything special to cause it? Are there other notable extensions being used in this example? If so you could try generating something without that to see if it's related.

What version of WebUI are you using? If you scroll all the way down in the WebUI you should see a line at the bottom with all the version numbers. You can share those if you want.

**Comment by TenaciousDean** [comment]
I'm away from my computer at the moment but thanks for getting back to me. Does A1111 update automatically? I've not manually updated since probably December or so. I'll be able to check on Monday

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Index154** [comment]
I'm not sure actually if automatic updates are enabled by default. It might depend on how you installed it too. In my case I cloned the github repository and my webui-user.bat has this line in it which makes it update every time I launch the WebUI:
`git pull`
I might have added it manually though, I don't remember.

**Comment by TenaciousDean** [comment]
I just checked and these are the versions I'm running at the bottom of A1111 (just including everything as not sure what might be relevant):

A1111 version: v1.6.1<https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7>  •  python: 3.10.0  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: c95a4e4a92<https://google.com/search?q=c95a4e4a9226c19cc666753b10ac63114e6a79c39c4fa093bc2998a10bd1dee2>
________________________________

**Comment by Index154** [comment]
Yea I'd suggest updating A1111 WebUI to the current version. The one you're using appears to be from November. Maybe also try updating your extensions to be safe. Perhaps you have an older ControlNet version installed as well.

But the error you had in your logs does point more towards it being an issue with the WebUI itself.

**Comment by Index154** [comment]
Ok yeah I just checked and the missing attribute causing your error was added to the WebUI's code in a commit from January. So if you update it the issue should be fixed for sure.

**Comment by TenaciousDean** [comment]
This worked perfectly! Thank you! Just needed to update lol
________________________________
